"""empty message

Revision ID: 417d0777e758
Revises: 7f5679a59902
Create Date: 2017-03-05 14:28:42.949895

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '417d0777e758'
down_revision = '7f5679a59902'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('acquisition',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('purchase_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['book.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('acquisition')
    # ### end Alembic commands ###
