"""empty message

Revision ID: 607fbe72cd9d
Revises: c381344c5f42
Create Date: 2017-03-05 14:09:58.547755

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '607fbe72cd9d'
down_revision = 'c381344c5f42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('edition',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('page_count', sa.Integer(), nullable=False),
    sa.Column('format', sa.Enum('PHYSICAL', 'DIGITAL', 'AUDIOBOOK', name='edition_format'), nullable=False),
    sa.Column('publisher', sa.String(length=255), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['book.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('edition')
    op.execute('DROP TYPE IF EXISTS edition_format')
    # ### end Alembic commands ###
