"""empty message

Revision ID: 829b6a377b01
Revises: c381344c5f42
Create Date: 2017-02-25 17:25:50.279389

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '829b6a377b01'
down_revision = 'c381344c5f42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=225), nullable=False),
    sa.Column('password', sa.String(length=225), nullable=False),
    sa.Column('email', sa.String(length=225), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('acquisition',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('purchase_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['book.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('edition',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('page_count', sa.Integer(), nullable=False),
    sa.Column('format', sa.Enum('PHYSICAL', 'DIGITAL', 'AUDIOBOOK', name='edition_format'), nullable=False),
    sa.Column('publisher', sa.String(length=255), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['book.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('edition')
    op.execute('DROP TYPE IF EXISTS edition_format')
    op.drop_table('acquisition')
    op.drop_table('user')
    # ### end Alembic commands ###
