"""empty message

Revision ID: c381344c5f42
Revises:
Create Date: 2017-02-25 15:54:56.689021

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c381344c5f42'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=225), nullable=False),
    sa.Column('author', sa.String(length=225), nullable=False),
    sa.Column('length_category', sa.Enum('NOVEL', 'NOVELETTE', 'NOVELLA', 'SHORT_STORY', 'ANTHOLOGY', 'GRAPHIC_NOVEL', name='book_length_category'), nullable=False),
    sa.Column('age_group', sa.Enum('ADULT', 'YOUNG_ADULT', 'MIDDLE_GRADE', 'EARLY_READER', name='book_age_group'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('book')
    op.execute('DROP TYPE IF EXISTS book_length_category')
    op.execute('DROP TYPE IF EXISTS book_age_group')
    # ### end Alembic commands ###
